# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from alpasim_carla._proto.alpasim_grpc.v0 import common_pb2 as alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2
from alpasim_carla._proto.alpasim_grpc.v0 import controller_pb2 as alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2


class VDCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_version = channel.unary_unary(
                '/controller.VDCService/get_version',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.VersionId.FromString,
                )
        self.start_session = channel.unary_unary(
                '/controller.VDCService/start_session',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2.VDCSessionRequest.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.SessionRequestStatus.FromString,
                )
        self.close_session = channel.unary_unary(
                '/controller.VDCService/close_session',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2.VDCSessionCloseRequest.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                )
        self.run_controller_and_vehicle = channel.unary_unary(
                '/controller.VDCService/run_controller_and_vehicle',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2.RunControllerAndVehicleModelRequest.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2.RunControllerAndVehicleModelResponse.FromString,
                )


class VDCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def close_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def run_controller_and_vehicle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VDCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_version': grpc.unary_unary_rpc_method_handler(
                    servicer.get_version,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.VersionId.SerializeToString,
            ),
            'start_session': grpc.unary_unary_rpc_method_handler(
                    servicer.start_session,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2.VDCSessionRequest.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.SessionRequestStatus.SerializeToString,
            ),
            'close_session': grpc.unary_unary_rpc_method_handler(
                    servicer.close_session,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2.VDCSessionCloseRequest.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            ),
            'run_controller_and_vehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.run_controller_and_vehicle,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2.RunControllerAndVehicleModelRequest.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2.RunControllerAndVehicleModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controller.VDCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VDCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.VDCService/get_version',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.VersionId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def start_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.VDCService/start_session',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2.VDCSessionRequest.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.SessionRequestStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def close_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.VDCService/close_session',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2.VDCSessionCloseRequest.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def run_controller_and_vehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.VDCService/run_controller_and_vehicle',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2.RunControllerAndVehicleModelRequest.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_controller__pb2.RunControllerAndVehicleModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
