# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from alpasim_carla._proto.alpasim_grpc.v0 import common_pb2 as alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2
from alpasim_carla._proto.alpasim_grpc.v0 import physics_pb2 as alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_physics__pb2


class PhysicsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ground_intersection = channel.unary_unary(
                '/physics.PhysicsService/ground_intersection',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_physics__pb2.PhysicsGroundIntersectionRequest.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_physics__pb2.PhysicsGroundIntersectionReturn.FromString,
                )
        self.get_version = channel.unary_unary(
                '/physics.PhysicsService/get_version',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.VersionId.FromString,
                )
        self.get_available_scenes = channel.unary_unary(
                '/physics.PhysicsService/get_available_scenes',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.AvailableScenesReturn.FromString,
                )


class PhysicsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ground_intersection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_available_scenes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhysicsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ground_intersection': grpc.unary_unary_rpc_method_handler(
                    servicer.ground_intersection,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_physics__pb2.PhysicsGroundIntersectionRequest.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_physics__pb2.PhysicsGroundIntersectionReturn.SerializeToString,
            ),
            'get_version': grpc.unary_unary_rpc_method_handler(
                    servicer.get_version,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.VersionId.SerializeToString,
            ),
            'get_available_scenes': grpc.unary_unary_rpc_method_handler(
                    servicer.get_available_scenes,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.AvailableScenesReturn.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physics.PhysicsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PhysicsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ground_intersection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/physics.PhysicsService/ground_intersection',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_physics__pb2.PhysicsGroundIntersectionRequest.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_physics__pb2.PhysicsGroundIntersectionReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/physics.PhysicsService/get_version',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.VersionId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_available_scenes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/physics.PhysicsService/get_available_scenes',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.AvailableScenesReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
