# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from alpasim_carla._proto.alpasim_grpc.v0 import common_pb2 as alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2
from alpasim_carla._proto.alpasim_grpc.v0 import runtime_pb2 as alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_runtime__pb2


class RuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.simulate = channel.unary_unary(
                '/RuntimeService/simulate',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_runtime__pb2.SimulationRequest.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_runtime__pb2.SimulationReturn.FromString,
                )
        self.get_runtime_info = channel.unary_unary(
                '/RuntimeService/get_runtime_info',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_runtime__pb2.RuntimeInfo.FromString,
                )
        self.shut_down = channel.unary_unary(
                '/RuntimeService/shut_down',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                )


class RuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def simulate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_runtime_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def shut_down(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'simulate': grpc.unary_unary_rpc_method_handler(
                    servicer.simulate,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_runtime__pb2.SimulationRequest.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_runtime__pb2.SimulationReturn.SerializeToString,
            ),
            'get_runtime_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_runtime_info,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_runtime__pb2.RuntimeInfo.SerializeToString,
            ),
            'shut_down': grpc.unary_unary_rpc_method_handler(
                    servicer.shut_down,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def simulate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RuntimeService/simulate',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_runtime__pb2.SimulationRequest.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_runtime__pb2.SimulationReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_runtime_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RuntimeService/get_runtime_info',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_runtime__pb2.RuntimeInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def shut_down(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RuntimeService/shut_down',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
