# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from alpasim_carla._proto.alpasim_grpc.v0 import common_pb2 as alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2
from alpasim_carla._proto.alpasim_grpc.v0 import traffic_pb2 as alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2


class TrafficServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.start_session = channel.unary_unary(
                '/traffic.TrafficService/start_session',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficSessionRequest.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.SessionRequestStatus.FromString,
                )
        self.close_session = channel.unary_unary(
                '/traffic.TrafficService/close_session',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficSessionCloseRequest.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                )
        self.simulate = channel.unary_unary(
                '/traffic.TrafficService/simulate',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficRequest.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficReturn.FromString,
                )
        self.get_metadata = channel.unary_unary(
                '/traffic.TrafficService/get_metadata',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficModuleMetadata.FromString,
                )


class TrafficServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def start_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def close_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def simulate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_metadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrafficServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'start_session': grpc.unary_unary_rpc_method_handler(
                    servicer.start_session,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficSessionRequest.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.SessionRequestStatus.SerializeToString,
            ),
            'close_session': grpc.unary_unary_rpc_method_handler(
                    servicer.close_session,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficSessionCloseRequest.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            ),
            'simulate': grpc.unary_unary_rpc_method_handler(
                    servicer.simulate,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficRequest.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficReturn.SerializeToString,
            ),
            'get_metadata': grpc.unary_unary_rpc_method_handler(
                    servicer.get_metadata,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficModuleMetadata.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'traffic.TrafficService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrafficService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def start_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/traffic.TrafficService/start_session',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficSessionRequest.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.SessionRequestStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def close_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/traffic.TrafficService/close_session',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficSessionCloseRequest.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def simulate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/traffic.TrafficService/simulate',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficRequest.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_metadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/traffic.TrafficService/get_metadata',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_traffic__pb2.TrafficModuleMetadata.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
