# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alpasim_carla/_proto/alpasim_grpc/v0/traffic.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from alpasim_carla._proto.alpasim_grpc.v0 import common_pb2 as alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2alpasim_carla/_proto/alpasim_grpc/v0/traffic.proto\x12\x07traffic\x1a\x31\x61lpasim_carla/_proto/alpasim_grpc/v0/common.proto\"|\n\x10ObjectTrajectory\x12\x1a\n\x04\x61\x61\x62\x62\x18\x01 \x01(\x0b\x32\x0c.common.AABB\x12&\n\ntrajectory\x18\x02 \x01(\x0b\x32\x12.common.Trajectory\x12\x11\n\tobject_id\x18\x03 \x01(\t\x12\x11\n\tis_static\x18\x04 \x01(\x08\"S\n\x16ObjectTrajectoryUpdate\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12&\n\ntrajectory\x18\x02 \x01(\x0b\x32\x12.common.Trajectory\"\xc5\x01\n\x15TrafficSessionRequest\x12\x14\n\x0csession_uuid\x18\x01 \x01(\t\x12\x0e\n\x06map_id\x18\x02 \x01(\t\x12\x13\n\x0brandom_seed\x18\x03 \x01(\x06\x12=\n\x1alogged_object_trajectories\x18\x04 \x03(\x0b\x32\x19.traffic.ObjectTrajectory\x12\x1d\n\x10handover_time_us\x18\x05 \x01(\x06H\x00\x88\x01\x01\x42\x13\n\x11_handover_time_us\"2\n\x1aTrafficSessionCloseRequest\x12\x14\n\x0csession_uuid\x18\x01 \x01(\t\"\x81\x01\n\x0eTrafficRequest\x12\x14\n\x0csession_uuid\x18\x01 \x01(\t\x12\x15\n\rtime_query_us\x18\x02 \x01(\x06\x12\x42\n\x19object_trajectory_updates\x18\x03 \x03(\x0b\x32\x1f.traffic.ObjectTrajectoryUpdate\"S\n\rTrafficReturn\x12\x42\n\x19object_trajectory_updates\x18\x01 \x03(\x0b\x32\x1f.traffic.ObjectTrajectoryUpdate\"|\n\x15TrafficModuleMetadata\x12%\n\nversion_id\x18\x01 \x01(\x0b\x32\x11.common.VersionId\x12!\n\x19minimum_history_length_us\x18\x02 \x01(\x06\x12\x19\n\x11supported_map_ids\x18\x03 \x03(\t2\xa0\x02\n\x0eTrafficService\x12M\n\rstart_session\x12\x1e.traffic.TrafficSessionRequest\x1a\x1c.common.SessionRequestStatus\x12\x43\n\rclose_session\x12#.traffic.TrafficSessionCloseRequest\x1a\r.common.Empty\x12;\n\x08simulate\x12\x17.traffic.TrafficRequest\x1a\x16.traffic.TrafficReturn\x12=\n\x0cget_metadata\x12\r.common.Empty\x1a\x1e.traffic.TrafficModuleMetadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alpasim_carla._proto.alpasim_grpc.v0.traffic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBJECTTRAJECTORY']._serialized_start=114
  _globals['_OBJECTTRAJECTORY']._serialized_end=238
  _globals['_OBJECTTRAJECTORYUPDATE']._serialized_start=240
  _globals['_OBJECTTRAJECTORYUPDATE']._serialized_end=323
  _globals['_TRAFFICSESSIONREQUEST']._serialized_start=326
  _globals['_TRAFFICSESSIONREQUEST']._serialized_end=523
  _globals['_TRAFFICSESSIONCLOSEREQUEST']._serialized_start=525
  _globals['_TRAFFICSESSIONCLOSEREQUEST']._serialized_end=575
  _globals['_TRAFFICREQUEST']._serialized_start=578
  _globals['_TRAFFICREQUEST']._serialized_end=707
  _globals['_TRAFFICRETURN']._serialized_start=709
  _globals['_TRAFFICRETURN']._serialized_end=792
  _globals['_TRAFFICMODULEMETADATA']._serialized_start=794
  _globals['_TRAFFICMODULEMETADATA']._serialized_end=918
  _globals['_TRAFFICSERVICE']._serialized_start=921
  _globals['_TRAFFICSERVICE']._serialized_end=1209
# @@protoc_insertion_point(module_scope)
