# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from alpasim_carla._proto.alpasim_grpc.v0 import common_pb2 as alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2
from alpasim_carla._proto.alpasim_grpc.v0 import video_model_pb2 as alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2


class WorldModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.start_session = channel.unary_unary(
                '/omnidreams.video_model.WorldModelService/start_session',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.SessionRequest.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.SessionId.FromString,
                )
        self.close_session = channel.unary_unary(
                '/omnidreams.video_model.WorldModelService/close_session',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.SessionCloseRequest.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                )
        self.render_video_chunk = channel.unary_unary(
                '/omnidreams.video_model.WorldModelService/render_video_chunk',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.VideoChunkRequest.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.VideoChunkReturn.FromString,
                )
        self.get_version = channel.unary_unary(
                '/omnidreams.video_model.WorldModelService/get_version',
                request_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.VersionId.FromString,
                )


class WorldModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def start_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def close_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def render_video_chunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorldModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'start_session': grpc.unary_unary_rpc_method_handler(
                    servicer.start_session,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.SessionRequest.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.SessionId.SerializeToString,
            ),
            'close_session': grpc.unary_unary_rpc_method_handler(
                    servicer.close_session,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.SessionCloseRequest.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            ),
            'render_video_chunk': grpc.unary_unary_rpc_method_handler(
                    servicer.render_video_chunk,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.VideoChunkRequest.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.VideoChunkReturn.SerializeToString,
            ),
            'get_version': grpc.unary_unary_rpc_method_handler(
                    servicer.get_version,
                    request_deserializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                    response_serializer=alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.VersionId.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omnidreams.video_model.WorldModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorldModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def start_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnidreams.video_model.WorldModelService/start_session',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.SessionRequest.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.SessionId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def close_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnidreams.video_model.WorldModelService/close_session',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.SessionCloseRequest.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def render_video_chunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnidreams.video_model.WorldModelService/render_video_chunk',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.VideoChunkRequest.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_video__model__pb2.VideoChunkReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnidreams.video_model.WorldModelService/get_version',
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            alpasim__carla_dot___proto_dot_alpasim__grpc_dot_v0_dot_common__pb2.VersionId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
