"""Blueprint catalogue: the ladder's data, loaded from a listing file.

Pure (gate G1). The curated 0.9.16 tables are wrong on 0.10 - none of the
eight vehicle ids survive - so the ladder reads its candidates from a file
that tools/list_blueprints.py writes against the server actually in use.
"""

import pytest

from alpasim_carla.catalog import (
    BlueprintUnavailable,
    canonical_listing,
    catalog_digest,
    default_catalog,
    load_catalog,
    parse_catalog,
)

LISTING = """\
# generated by tools/list_blueprints.py
# server=0.10.0 map=/Game/Carla/Maps/Town10HD_Opt
# fallback_blueprint: static.prop.box03
# id	category	length	width	height
vehicle.mini.cooper	vehicle	3.80	1.92	1.45
vehicle.lincoln.mkz	vehicle	4.90	2.13	1.51
vehicle.firetruck.actors	vehicle	8.49	2.94	3.41
walker.pedestrian.0001	walker	0.0	0.0	0.0
static.prop.box03	prop	0.0	0.0	0.0
"""


def test_parses_vehicles_with_dims_in_file_order():
    catalog = parse_catalog(LISTING)
    assert catalog.vehicles == [
        ("vehicle.mini.cooper", (3.80, 1.92, 1.45)),
        ("vehicle.lincoln.mkz", (4.90, 2.13, 1.51)),
        ("vehicle.firetruck.actors", (8.49, 2.94, 3.41)),
    ]


def test_comments_and_blank_lines_are_ignored():
    catalog = parse_catalog("\n\n# only a comment\n" + LISTING)
    assert len(catalog.vehicles) == 3


def test_walker_is_the_first_walker_entry():
    assert parse_catalog(LISTING).walker == "walker.pedestrian.0001"


def test_fallback_prop_is_the_field_the_listing_declares():
    assert parse_catalog(LISTING).fallback_prop == "static.prop.box03"


def test_the_declared_field_wins_over_any_preference_this_reader_might_have():
    """The terminal fallback is a per-image fact, so the reader has no
    opinion: box03 is listed here and advertisement is declared, and the
    declaration is what the ladder degrades to. The old reader preferred
    box03 by constant, which on 0.10 named a blueprint the server does not
    have at all."""
    listing = LISTING.replace(
        "# fallback_blueprint: static.prop.box03",
        "# fallback_blueprint: static.prop.advertisement",
    ) + "static.prop.advertisement\tprop\t0\t0\t0\n"
    assert parse_catalog(listing).fallback_prop == "static.prop.advertisement"


def test_a_listing_without_the_field_is_refused_by_name(tmp_path):
    """An older listing predates the field. It is not tolerated by accident
    - the reader says so and names what to regenerate."""
    listing = "\n".join(
        line
        for line in LISTING.splitlines()
        if not line.startswith("# fallback_blueprint:")
    )
    with pytest.raises(BlueprintUnavailable) as exc:
        parse_catalog(listing, source="blueprints_0.10.txt")
    message = str(exc.value)
    assert "fallback_blueprint:" in message
    assert "tools/list_blueprints.py" in message
    assert "blueprints_0.10.txt" in message


def test_a_declared_fallback_the_listing_does_not_list_is_refused():
    """The generator writes the field only after verifying the blueprint on
    the server, so a file that names a prop it does not list was edited by
    hand and its claim is unverified."""
    listing = LISTING.replace(
        "# fallback_blueprint: static.prop.box03",
        "# fallback_blueprint: static.prop.advertisement",
    )
    with pytest.raises(BlueprintUnavailable, match="static.prop.advertisement"):
        parse_catalog(listing)


def test_two_disagreeing_declarations_are_an_error():
    listing = LISTING + "# fallback_blueprint: static.prop.streetbarrier\n"
    with pytest.raises(ValueError, match="fallback_blueprint"):
        parse_catalog(listing)


def test_membership_reports_every_listed_id():
    catalog = parse_catalog(LISTING)
    assert catalog.has("vehicle.lincoln.mkz")
    assert not catalog.has("vehicle.tesla.model3")


def test_two_wheelers_may_be_absent_on_010():
    """0.10 removed the motorcycle and bicycle categories outright."""
    assert parse_catalog(LISTING).two_wheelers == []


def test_a_listing_with_no_prop_fails_at_load_not_at_spawn():
    """The old ladder called find() on the box id with no guard, so a missing
    prop raised IndexError out of _spawn mid-rollout. Fail at startup."""
    listing = "\n".join(
        line for line in LISTING.splitlines() if not line.startswith("static.")
    )
    with pytest.raises(BlueprintUnavailable, match="no prop blueprint"):
        parse_catalog(listing)


def test_a_listing_with_no_vehicles_fails_at_load():
    listing = "\n".join(
        line for line in LISTING.splitlines() if not line.startswith("vehicle.")
    )
    with pytest.raises(BlueprintUnavailable, match="no vehicle blueprint"):
        parse_catalog(listing)


def test_a_listing_with_no_walker_fails_at_load():
    listing = "\n".join(
        line for line in LISTING.splitlines() if not line.startswith("walker.")
    )
    with pytest.raises(BlueprintUnavailable, match="no walker blueprint"):
        parse_catalog(listing)


def test_malformed_row_names_the_line_number():
    listing = LISTING + "vehicle.broken\tvehicle\tnot-a-number\t1.0\t1.0\n"
    with pytest.raises(ValueError, match="line 10"):
        parse_catalog(listing)


def test_load_catalog_reads_a_file(tmp_path):
    path = tmp_path / "blueprints_0.10.txt"
    path.write_text(LISTING)
    assert load_catalog(str(path)).walker == "walker.pedestrian.0001"


def test_there_is_no_default_catalog_any_more():
    """The curated 0.9.16 table was reachable by not passing a catalogue,
    and on 0.10 every one of its rows is wrong - so the run it enabled
    rendered boxes and scored them. It now refuses instead."""
    with pytest.raises(BlueprintUnavailable):
        default_catalog()


def test_the_refusal_names_the_tool_that_produces_a_listing():
    """Whoever hits this on day one must not have to read catalog.py."""
    with pytest.raises(BlueprintUnavailable) as exc:
        default_catalog()
    message = str(exc.value)
    assert "tools/list_blueprints.py" in message
    assert "--blueprint-catalog" in message


def test_load_failure_names_the_file_and_the_command_that_rebuilds_it(tmp_path):
    """Whoever hits this on day one must not have to read catalog.py to find
    out what to run."""
    path = tmp_path / "blueprints_0.10.txt"
    path.write_text(
        "\n".join(
            line for line in LISTING.splitlines() if not line.startswith("static.")
        )
    )
    with pytest.raises(BlueprintUnavailable) as exc:
        load_catalog(str(path))
    message = str(exc.value)
    assert "blueprints_0.10.txt" in message
    assert "tools/list_blueprints.py" in message


def test_every_load_time_failure_carries_the_regeneration_command():
    for dropped in ("vehicle.", "walker.", "static."):
        listing = "\n".join(
            line for line in LISTING.splitlines() if not line.startswith(dropped)
        )
        with pytest.raises(BlueprintUnavailable) as exc:
            parse_catalog(listing, source="blueprints_0.10.txt")
        assert "tools/list_blueprints.py" in str(exc.value)


# -- catalogue digest ---------------------------------------------------------


def test_the_digest_is_a_sha256_of_the_catalogue_content():
    digest = catalog_digest(parse_catalog(LISTING))
    algorithm, _, hexdigest = digest.partition(":")
    assert algorithm == "sha256"
    assert len(hexdigest) == 64
    assert set(hexdigest) <= set("0123456789abcdef")


def test_the_canonical_form_carries_the_declared_fallback():
    """The canonical form drops comments - except this one, which is data.
    Without it the re-emitted listing would not parse back."""
    canonical = canonical_listing(parse_catalog(LISTING))
    assert "# fallback_blueprint: static.prop.box03" in canonical
    assert parse_catalog(canonical).fallback_prop == "static.prop.box03"


def test_the_digest_survives_reserialisation():
    """The manifest records the digest; the listing file it came from can
    be rewritten. Re-emitting the catalogue and parsing it back must not
    move the value, or the record would look like a different catalogue."""
    catalog = parse_catalog(LISTING)
    reparsed = parse_catalog(canonical_listing(catalog))
    assert catalog_digest(reparsed) == catalog_digest(catalog)


def test_the_digest_ignores_comments_whitespace_and_the_source_name(tmp_path):
    """Two files that make the ladder choose identically are the same
    catalogue, whatever they are called."""
    path = tmp_path / "somewhere_else.txt"
    path.write_text("\n# regenerated on another box\n\n" + LISTING)
    assert catalog_digest(load_catalog(str(path))) == catalog_digest(
        parse_catalog(LISTING)
    )


def test_the_digest_changes_when_a_vehicle_rung_changes():
    swapped = LISTING.replace("vehicle.lincoln.mkz", "vehicle.ue4.lincoln.mkz")
    assert catalog_digest(parse_catalog(swapped)) != catalog_digest(
        parse_catalog(LISTING)
    )


def test_the_digest_changes_when_a_dimension_changes():
    """Dimensions decide nearest-dims selection, so they are part of the
    catalogue's behaviour, not decoration."""
    resized = LISTING.replace("4.90\t2.13\t1.51", "5.90\t2.13\t1.51")
    assert catalog_digest(parse_catalog(resized)) != catalog_digest(
        parse_catalog(LISTING)
    )


def test_the_digest_changes_when_the_vehicle_order_changes():
    """Order breaks ties in nearest-dims, so two orderings are two
    catalogues even with the same ids."""
    reordered = parse_catalog(LISTING)
    reordered.vehicles.reverse()
    assert catalog_digest(reordered) != catalog_digest(parse_catalog(LISTING))


def test_the_digest_changes_when_the_walker_or_the_prop_changes():
    base = catalog_digest(parse_catalog(LISTING))
    walker = LISTING.replace("walker.pedestrian.0001", "walker.pedestrian.0042")
    prop = LISTING.replace("static.prop.box03", "static.prop.streetbarrier")
    assert catalog_digest(parse_catalog(walker)) != base
    assert catalog_digest(parse_catalog(prop)) != base


def test_the_digest_changes_when_an_id_is_added_to_membership():
    """Membership is a rung too: a manifest override naming an id the
    server does not have degrades to the prop."""
    extra = LISTING + "static.prop.trafficcone01\tprop\t0\t0\t0\n"
    assert catalog_digest(parse_catalog(extra)) != catalog_digest(
        parse_catalog(LISTING)
    )
