"""Blueprint catalogue: the ladder's data, loaded from a listing file.

Pure (gate G1). The curated 0.9.16 tables are wrong on 0.10 - none of the
eight vehicle ids survive - so the ladder reads its candidates from a file
that tools/list_blueprints.py writes against the server actually in use.
"""

import pytest

from alpasim_carla.catalog import (
    BlueprintUnavailable,
    default_catalog,
    load_catalog,
    parse_catalog,
)

LISTING = """\
# generated by tools/list_blueprints.py
# server=0.10.0 map=/Game/Carla/Maps/Town10HD_Opt
# id	category	length	width	height
vehicle.mini.cooper	vehicle	3.80	1.92	1.45
vehicle.lincoln.mkz	vehicle	4.90	2.13	1.51
vehicle.firetruck.actors	vehicle	8.49	2.94	3.41
walker.pedestrian.0001	walker	0.0	0.0	0.0
static.prop.box03	prop	0.0	0.0	0.0
"""


def test_parses_vehicles_with_dims_in_file_order():
    catalog = parse_catalog(LISTING)
    assert catalog.vehicles == [
        ("vehicle.mini.cooper", (3.80, 1.92, 1.45)),
        ("vehicle.lincoln.mkz", (4.90, 2.13, 1.51)),
        ("vehicle.firetruck.actors", (8.49, 2.94, 3.41)),
    ]


def test_comments_and_blank_lines_are_ignored():
    catalog = parse_catalog("\n\n# only a comment\n" + LISTING)
    assert len(catalog.vehicles) == 3


def test_walker_is_the_first_walker_entry():
    assert parse_catalog(LISTING).walker == "walker.pedestrian.0001"


def test_fallback_prop_prefers_box03_when_present():
    assert parse_catalog(LISTING).fallback_prop == "static.prop.box03"


def test_fallback_prop_falls_back_to_any_prop_when_box03_absent():
    listing = LISTING.replace("static.prop.box03", "static.prop.streetbarrier")
    assert parse_catalog(listing).fallback_prop == "static.prop.streetbarrier"


def test_membership_reports_every_listed_id():
    catalog = parse_catalog(LISTING)
    assert catalog.has("vehicle.lincoln.mkz")
    assert not catalog.has("vehicle.tesla.model3")


def test_two_wheelers_may_be_absent_on_010():
    """0.10 removed the motorcycle and bicycle categories outright."""
    assert parse_catalog(LISTING).two_wheelers == []


def test_a_listing_with_no_prop_fails_at_load_not_at_spawn():
    """The old ladder called find() on the box id with no guard, so a missing
    prop raised IndexError out of _spawn mid-rollout. Fail at startup."""
    listing = "\n".join(
        line for line in LISTING.splitlines() if not line.startswith("static.")
    )
    with pytest.raises(BlueprintUnavailable, match="no prop blueprint"):
        parse_catalog(listing)


def test_a_listing_with_no_vehicles_fails_at_load():
    listing = "\n".join(
        line for line in LISTING.splitlines() if not line.startswith("vehicle.")
    )
    with pytest.raises(BlueprintUnavailable, match="no vehicle blueprint"):
        parse_catalog(listing)


def test_a_listing_with_no_walker_fails_at_load():
    listing = "\n".join(
        line for line in LISTING.splitlines() if not line.startswith("walker.")
    )
    with pytest.raises(BlueprintUnavailable, match="no walker blueprint"):
        parse_catalog(listing)


def test_malformed_row_names_the_line_number():
    listing = LISTING + "vehicle.broken\tvehicle\tnot-a-number\t1.0\t1.0\n"
    with pytest.raises(ValueError, match="line 9"):
        parse_catalog(listing)


def test_load_catalog_reads_a_file(tmp_path):
    path = tmp_path / "blueprints_0.10.txt"
    path.write_text(LISTING)
    assert load_catalog(str(path)).walker == "walker.pedestrian.0001"


def test_default_catalog_is_the_curated_0916_table():
    catalog = default_catalog()
    assert catalog.has("vehicle.tesla.model3")
    assert catalog.fallback_prop == "static.prop.box03"
    assert [bp for bp, _ in catalog.two_wheelers] == [
        "vehicle.diamondback.century",
        "vehicle.yamaha.yzf",
    ]


def test_default_catalog_reports_unknown_ids_as_absent():
    assert not default_catalog().has("vehicle.lincoln.mkz")


def test_load_failure_names_the_file_and_the_command_that_rebuilds_it(tmp_path):
    """Whoever hits this on day one must not have to read catalog.py to find
    out what to run."""
    path = tmp_path / "blueprints_0.10.txt"
    path.write_text(
        "\n".join(
            line for line in LISTING.splitlines() if not line.startswith("static.")
        )
    )
    with pytest.raises(BlueprintUnavailable) as exc:
        load_catalog(str(path))
    message = str(exc.value)
    assert "blueprints_0.10.txt" in message
    assert "tools/list_blueprints.py" in message


def test_every_load_time_failure_carries_the_regeneration_command():
    for dropped in ("vehicle.", "walker.", "static."):
        listing = "\n".join(
            line for line in LISTING.splitlines() if not line.startswith(dropped)
        )
        with pytest.raises(BlueprintUnavailable) as exc:
            parse_catalog(listing, source="blueprints_0.10.txt")
        assert "tools/list_blueprints.py" in str(exc.value)
